replicaCount: 1

workloadName: wedding-shahnazia-checkin

image:
  name: luqmanarfian/wedding-shahnazia-checkin
  pullPolicy: Always

volumeMounts:
  enabled: false

secret:
  enabled: false

#using yaml format
env:
#  - name: NODE_ENV
#    value: "production"
#  - name: OPENSSL_CONF
#    value: "/dev/null"
#  - name: NODE_OPTIONS
#    value: --max-old-space-size=6144

#using yaml format
hostAliases: {}

container:
  port: 3000

readinessProbe:
  path: /
  scheme: HTTP
  initialDelaySeconds: 15
  periodSeconds: 5

#using yaml format
resources:
  limits:
    cpu: "15m"
    memory: "25Mi"
    ephemeral-storage: 128Mi

  requests:
    cpu: "10m"
    memory: "20Mi"
    ephemeral-storage: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

#using yaml format
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - luqman-server

service:
  type: ClusterIP
  port: 80
  targetPort: 3000
  protocol: TCP

ingress:
  enabled: false
