apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.workloadName }}
  labels:
    app: {{ .Values.workloadName }}
    {{- include "wedding-shahnazia-checkin-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.workloadName }}
      {{- include "wedding-shahnazia-checkin-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.workloadName }}
        {{- include "wedding-shahnazia-checkin-chart.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Values.workloadName }}
          image: {{ .Values.image.name }}
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.volumeMounts.enabled }}
          volumeMounts:
            - name: {{ .Values.volumeMounts.name }}
              mountPath: {{ .Values.volumeMounts.mountPath }}
          {{- end }}
          ports:
            - name: liveness-port
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: liveness-port
              scheme: {{ .Values.readinessProbe.scheme }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if .Values.secret.enabled }}
      volumes:
        - name: {{ .Values.volumeMounts.name }}
          secret:
            secretName: {{ .Values.secret.name }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- . | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
