{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.workloadName }}-ingress
  labels:
    {{- include "wedding-shahnazia-checkin-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
    {{- end }}
  {{- end }}  
  {{- with .Values.ingress.defaultBackend }}
  defaultBackend:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
  {{- with .Values.ingress.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}